version: 2
jobs:
  build:

    working_directory: ~/mjb-coffee-service

    docker:
      - image: circleci/openjdk:11-browsers-legacy
        environment:

          MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          key:
            -v1-dependencies-{{ checksum "pom.xml" }}
            -v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key:
            -v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/mjb-coffee-service-0.0.1-SNAPSHOT.jar